apiVersion: apps/v1
kind: Deployment

metadata:
  name: application
  namespace: jenkins

spec:
  replicas: 1

  selector:
    matchLabels:
      app: application

  template:
    metadata:
      labels:
        app: application

    spec:
      containers:
        - name: application

          image: REPOSITORY_URL:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            # Application
            - name: PORT
              value: "8080"

            # AWS 
            - name: AWS_REGION
              value: "eu-west-2"

            - name: QUEUE_URL
              value: "QUEUE_URL"

            # PostgreSQL
            - name: DB_HOST
              value: "postgres"

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              value: "orders"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 256Mi