apiVersion: v1
kind: ServiceAccount

metadata:
  name: application-sa
  namespace: jenkins

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::893061519920:role/jenkins-application-role