# -----------------------------------------------------------------------------
# Application Service Account
#
# Purpose:
# Provides the Kubernetes identity used by the application workload.
#
# The Service Account is mapped to an AWS IAM Role using IAM Roles for Service
# Accounts (IRSA), allowing the application to access AWS services without
# storing long-lived AWS credentials inside the Kubernetes cluster.
# -----------------------------------------------------------------------------

apiVersion: v1
kind: ServiceAccount

metadata:
  name: application-sa
  namespace: jenkins

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::893061519920:role/jenkins-application-role