apiVersion: v1
kind: Pod
metadata:
  name: postgres-restore-test
  namespace: jenkins
spec:
  restartPolicy: Never
  containers:
    - name: restore-test
      image: postgres:16.9
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: restored-volume
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: restored-volume
      persistentVolumeClaim:
        claimName: postgres-data-restore
