# -----------------------------------------------------------------------------
# Development Application Overlay
# -----------------------------------------------------------------------------

resources:
  - ../../base
