apiVersion: v1
kind: Pod

metadata:
  name: restore-test
  namespace: jenkins

spec:
  containers:
    - name: restore-test
      image: busybox
      command: ["sleep", "3600"]

      volumeMounts:
        - name: restored-volume
          mountPath: /data

  volumes:
    - name: restored-volume
      persistentVolumeClaim:
        claimName: jenkins-pvc-restore