# -----------------------------------------------------------------------------
# PostgreSQL StatefulSet
#
# Purpose:
# Manages a set of identical pods with stable network identities and persistent storage.
# -----------------------------------------------------------------------------

apiVersion: apps/v1
kind: StatefulSet

# -----------------------------------------------------------------------------
# Uses the PostgreSQL Headless Service to provide each StatefulSet Pod
# with a stable DNS name and network identity.
# -----------------------------------------------------------------------------

metadata:
  name: postgres
  namespace: jenkins

spec:
  serviceName: postgres
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:

        - name: postgres
          image: postgres:16.9
          ports:
            - containerPort: 5432
              name: postgres

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:

    - metadata:
        name: postgres-data

      spec:

        accessModes:
          - ReadWriteOnce

        storageClassName: gp3-retain

        resources:
          requests:
            storage: 20Gi    