apiVersion: v1
kind: Service
metadata:
  name: scheduler
  labels:
    app: scheduler
  namespace: jenkins
spec:
  type: ClusterIP
  selector:
    app: scheduler
  ports:
    - name: http
      port: 8091
      targetPort: http
