# -----------------------------------------------------------------------------
# Jenkins Ingress
#
# Purpose:
# Exposes Jenkins through Traefik using the AWS Network Load Balancer.
# TLS certificates are issued and renewed by cert-manager through
# Let's Encrypt DNS-01 validation using the delegated Route 53 zone.
#
# -----------------------------------------------------------------------------

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: jenkins.mud-as-sir.uk

spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - jenkins.mud-as-sir.uk
      secretName: jenkins-tls

  rules:
    - host: jenkins.mud-as-sir.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins-service
                port:
                  number: 8080