# -----------------------------------------------------------------------------
# Jenkins Kustomization
#
# Purpose:
# Defines the Kubernetes resources that make up the Jenkins platform.
#
# Kustomize uses this file as the entry point for deploying the Jenkins
# Deployment, Service, Ingress and Persistent Volume Claim.
# -----------------------------------------------------------------------------

resources:
  - jenkins-deployment.yaml
  - jenkins-service.yaml
  - jenkins-ingress.yaml
  - jenkins-pvc.yaml