# -----------------------------------------------------------------------------
# Redis Kustomization
#
# Defines the Kubernetes resources required to deploy Redis.
# -----------------------------------------------------------------------------

resources:
  - redis-deployment.yaml
  - redis-service.yaml
  - redis-secret.yaml
