# -----------------------------------------------------------------------------
# Redis Password
#
# Generates the Redis authentication password through External Secrets.
# The generated value is stored in a Kubernetes Secret and is not committed
# to Git.
# -----------------------------------------------------------------------------

apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: redis-password
  namespace: jenkins

spec:
  length: 32
  digits: 6
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - REDIS_PASSWORD

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: jenkins

spec:
  refreshInterval: 1h

  target:
    name: redis-secret
    creationPolicy: Owner

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: redis-password
