# -----------------------------------------------------------------------------
# Redis StatefulSet
#
# Purpose:
# Runs Redis as a persistent stateful workload.
#
# Redis uses:
# - A 10Gi gp3 PVC created by volumeClaimTemplates
# - AOF persistence
# - Password authentication
# - Kubernetes health probes
# -----------------------------------------------------------------------------

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: jenkins

spec:
  serviceName: redis
  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: redis
          image: redis:8.2

          ports:
            - containerPort: 6379
              name: redis

          command:
            - sh
            - -c
            - exec redis-server --appendonly yes --requirepass "$REDIS_PASSWORD"

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli ping | grep -q PONG
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli ping | grep -q PONG
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: redis-data
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: redis-data

      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: gp3

        resources:
          requests:
            storage: 10Gi
