# -----------------------------------------------------------------------------
# Production Application Overlay
# -----------------------------------------------------------------------------

resources:
  - ../../base
