# -----------------------------------------------------------------------------
# Production Application Overlay
# -----------------------------------------------------------------------------

resources:
  - ../../base

patches:
  - path: patches/hpa-scaling.yaml
