# Restoring a PVC from a VolumeSnapshot

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: jenkins-pvc-restore
  namespace: jenkins

spec:
  storageClassName: gp3

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  dataSource:
    name: jenkins-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io

