apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: api-gateway
  namespace: monitoring
  labels:
    monitoring: prometheus
spec:
  namespaceSelector:
    matchNames:
      - jenkins
  selector:
    matchLabels:
      app: api-gateway
  targetLabels:
    - app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
