apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-service
  namespace: monitoring
  labels:
    monitoring: prometheus
spec:
  namespaceSelector:
    matchNames:
      - jenkins
  selector:
    matchLabels:
      app: payment-service
  targetLabels:
    - app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
