# -----------------------------------------------------------------------------
# External Secrets Configuration
#
# Purpose:
# Defines the Kubernetes resources required to securely synchronize application
# secrets from AWS Secrets Manager into the Kubernetes cluster.
# -----------------------------------------------------------------------------

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets