apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: grafana-secret
    creationPolicy: Owner

  data:
    - secretKey: admin-user
      remoteRef:
        key: jenkins/grafana
        property: GF_SECURITY_ADMIN_USER

    - secretKey: admin-password
      remoteRef:
        key: jenkins/grafana
        property: GF_SECURITY_ADMIN_PASSWORD
