# -----------------------------------------------------------------------------
# External Secrets Kustomization
#
# Purpose:
# Defines the Kubernetes resources managed together for the External Secrets
# configuration.
# -----------------------------------------------------------------------------

resources:
  - serviceaccount.yaml
  - cluster-secret-store.yaml
  - postgres-external-secret.yaml