# -----------------------------------------------------------------------------
# External Secrets Service Account
#
# Purpose:
# Defines the Kubernetes ServiceAccount used by External Secrets to access
# AWS Secrets Manager through IAM Roles for Service Accounts (IRSA).
# -----------------------------------------------------------------------------

apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::893061519920:role/jenkins-external-secrets-role